swagger: '2.0'
info:
  x-ibm-name: pokemon
  title: pokemon
  version: 1.0.0
schemes:
  - https
host: $(catalog.host)
basePath: /api
consumes:
  - application/json
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
    description: ''
security:
  - clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
      - operation-switch:
          title: operation-switch
          case:
            - operations:
                - verb: get
                  path: /pokemon
              execute:
                - invoke:
                    title: invoke
                    timeout: 60
                    verb: GET
                    cache-response: protocol
                    cache-ttl: 900
                    version: 1.0.0
                    target-url: 'https://pokemons.mybluemix.net/api/pokemons/'
            - operations:
                - verb: get
                  path: '/pokemon/{id}'
              execute:
                - invoke:
                    title: invoke
                    timeout: 60
                    verb: GET
                    cache-response: protocol
                    cache-ttl: 900
                    version: 1.0.0
                    target-url: 'https://pokemons.mybluemix.net/api/pokemons/{id}'
                - gatewayscript:
                    title: gatewayscript
                    version: 1.0.0
                    source: "\t//get the payload\n\tvar json = apim.getvariable('message');\n\tconsole.info(\"json %s\", JSON.stringify(json));\n\n\t//code to inject new attribute \n\tif (json.body && json.status.code == '200') {\n\t\tjson.body.platform = 'Powered by IBM API Connect';\n\t\tjson.headers.platform = 'Powered by IBM API Connect';\n\t}\n\telse {\n\tconsole.error(\"throwing apim error %s\", JSON.stringify(json.status.code));\n\t\tapim.error('ConnectionError', 500, 'Service Error', 'Failed to retrieve data');\n\t}\n\n\t//set the payload\n\tapim.setvariable('message.body', json.body);\n\tapim.setvariable('message.headers', json.headers);"
          otherwise: []
          version: 1.0.0
    catch:
      - errors:
          - ConnectionError
          - RuntimeError
        execute:
          - set-variable:
              title: Rewrite Error
              actions:
                - set: message.body
                  value: '{"message": "Unable to find Pokemon."}'
              version: 1.0.0
  gateway: datapower-gateway
paths:
  '/pokemon/{id}':
    get:
      responses:
        '200':
          description: 200 OK
    parameters:
      - name: id
        type: string
        required: true
        in: path
  /pokemon:
    get:
      responses:
        '200':
          description: 200 OK
    post:
      responses:
        '200':
          description: 200 OK
      parameters:
        - $ref: '#/parameters/Authorization'
definitions: {}
tags: []
produces:
  - application/json
parameters:
  Authorization:
    name: Authorization
    type: string
    required: false
    in: header
